### ISSUE TITLE
Test cases are not getting executed in existing project. Also getting an empty file in the email attachment.

### ISSUE THREAD

**Issue by 012Abu-Bakar** [anshooarora/chaintest#20]
![bug](https://github.com/user-attachments/assets/77a7cb76-3a67-4458-be79-7244dd1e7a97)

After test execution..
10:07:59.053 [main] ERROR com.aventstack.chaintest.generator.FileGenerator -- Error processing template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> build.runStats[1]  [in template "index.ftl" at line 102, column 21]

----
Tip: It's the final [] step that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${build.runStats[1].passed}  [in template "index.ftl" at line 102, column 19]

**Comment by anshooarora** [comment]
What version did you use? I believe this was resolved in the latest 1.0.4.

**Comment by 012Abu-Bakar** [comment]
yes, I've updated the version. Still not working
![image](https://github.com/user-attachments/assets/be11e6f6-acfd-4ec1-abf8-c73e014b03b6)

**Comment by anshooarora** [comment]
You don't need to add the chaintest-core dependency, or any other chaintest dependencies if testng adapter is all you need.  All you need is chaintest-testng.

**Comment by anshooarora** [comment]
You can refer this example:  https://github.com/anshooarora/chaintest/blob/main/examples/chaintest-testng-example/pom.xml

**Comment by anshooarora** [comment]
However, this is may be an issue on [L:149](https://github.com/anshooarora/chaintest/blob/main/core/chaintest-core-java/src/main/resources/com/aventstack/chaintest/generator/simple/index.ftl#L149) which you have just shared. Looking into it.

**Comment by anshooarora** [comment]
Added handling in case the object (RunStats) on L:149 isn't available.  It's still concerning why this would error out since the TestNG plugin enforces a 3-level depth:

```
- Suite
 - Class
  - Method
```

Can you retry with `1.0.5-SNAPSHOT`?

Sicne this is a snapshot release, you *may* have to enable your projects to download snapshots.  A simple way is to add the following to your pom.xml and run:  `mvn dependency:copy-dependencies -U`

```
<repositories>
    <repository>
      <id>nexus</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
  </repository>
</repositories>
```

**Comment by 012Abu-Bakar** [comment]
I realized that when I am using Listeners(in setup file or xml) then this issue occurring

@Listeners(ChainTestListener.class)
public class Setup {
	public WebDriver driver;
	
Or

<listeners>
<listener class-name="com.aventstack.chaintest.plugins.ChainTestListener"></listener>
</listeners>

**Comment by anshooarora** [comment]
There have been several reports of this issue occuring when using both `chaintest` and `extentreports` dependencies.  Is that the same scenario in your case?  The fix is to also explicitly include the `freemarker` dependency, which I believe conflicts due to the older version that `extentreports` is using.

If this does not resolve the issue, feel free to re-open this or a new issue.  Cheers.
